{{- if and .Values.featureFlags.enabled .Values.featureFlags.createSecret .Values.featureFlags.fmKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.featureFlags.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "squid-ui.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.featureFlags.secretKey }}: {{ .Values.featureFlags.fmKey | b64enc | quote }}
{{- end }}